DROP SCHEMA IF EXISTS DELIVERY CASCADE;

CREATE SCHEMA DELIVERY;

CREATE TABLE DELIVERY.ORDERS
(
    "ORD_ID" bigint NOT NULL,
    "ORD_DATE" timestamp(6) without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("ORD_ID")
);
